//Please take my late work I thought it was due tuesday and I had a lot of homework O_O
public class Main {

    public static void main(String[] args){

    System.out.println("\t\"I love Crescendo Cafe ramen\" \n");
    System.out   .        println("\\You should get it so the robtics team can get money");
    
    //COMMENTCOMMENTCOMMENT
    /*
    Random notes!
    n makes a new line
    t makes a tab
    ln makes a new line automatically with the print staement
    everything goes in the class and stuff I guess
    sysout then ctrl + space makes a print statement for you (haha jk this is only in eclipse ;-;)
    spaces don't matter in code that much
    */

    } 

}