public class Main{
public static void main(String[] args){
    
    int x = 123; //declaring the variable and assigning it. Initialiwhatever

    long y = 849035688075847L; //you put an "L" at the end because because

    byte z = 127; //you can only store up to 127 in bytes

    float a = 9.99f; //you put "f" at the end because because

    double b = 9.999999; //double is literally just float but better. Does not require "f"

    boolean c = false; //true or false

    char d = '@'; //one thing

    String e = "AAAAAAAAAAAAAAAAAAAAAAAAAAA"; //Text



    System.out.println(x); //printing the variable

    System.out.println("My really cool number is " + x); //printing string and integer with catenawhatever

    System.out.println("My really long number is " + y); //printing string and long with catenawhatever

        System.out.println("My really bite-sized number is " + z); //printing string and byte with catenawhatever

        System.out.println("My really floaty number is " + a); //printing string and float with catenawhatever

        System.out.println("My really double-floaty number is " + b); //printing string and double with catenawhatever

        System.out.println("My really booly statement is " + c); //printing string and boolean with catenawhatever

        System.out.println("My really chary statement is " + d); //printing string and char with catenawhatever

        System.out.println("My really stringy statement is " + e); //printing string and string with catenawhatever


    }
}